In [7]:
import pandas as pd


In [13]:
data=pd.read_csv('data.csv')

In [15]:
data=pd.read_csv('data.csv')

In [12]:
data=pd.read_csv(r"C:\Users\Yash\Downloads\yash.csv")

In [14]:
data.head()

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2023                     Level 1                99999       All industries   
1  2023                     Level 1                99999       All industries   
2  2023                     Level 1                99999       All industries   
3  2023                     Level 1                99999       All industries   
4  2023                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   

    Value                             Industry_code_ANZSIC06  
0  930995  ANZSIC06 divisions A-S (excluding classes K633...  
1  821630  ANZSIC06 divisions A-S (excluding classes K633...  
2   84354  ANZSIC06 divisions A-S (excluding classes K633...  
3   25010  ANZSIC06 divisions A-S (excluding classes K633...  
4  832964  ANZSIC06 divisions A-S (excluding classes K633...

In [16]:
data.tail()

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
50980  2013                     Level 3                 ZZ11   
50981  2013                     Level 3                 ZZ11   
50982  2013                     Level 3                 ZZ11   
50983  2013                     Level 3                 ZZ11   
50984  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC       Units Variable_code  \
50980  Food product manufacturing  Percentage           H37   
50981  Food product manufacturing  Percentage           H38   
50982  Food product manufacturing  Percentage           H39   
50983  Food product manufacturing  Percentage           H40   
50984  Food product manufacturing  Percentage           H41   

                             Variable_name Variable_category Value  \
50980                          Quick ratio  Financial ratios    52   
50981  Margin on sales of goods for resale  Financial ratios    40   
50982                     Return on equity  Financial ratios    12   
50983               Return on total assets  Financial ratios     5   
50984                Liabilities structure  Financial ratios    46   

                                  Industry_code_ANZSIC06  
50980  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50981  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50982  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50983  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50984  ANZSIC06 groups C111, C112, C113, C114, C115, ...

In [21]:
data.shape

(50985, 10)

In [20]:
data.shape

(50985, 10)

In [24]:
data.describe()

Year
count  50985.000000
mean    2018.000000
std        3.162309
min     2013.000000
25%     2015.000000
50%     2018.000000
75%     2021.000000
max     2023.000000

In [28]:
data.iloc[0:5,0:3]

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC
0  2023                     Level 1                99999
1  2023                     Level 1                99999
2  2023                     Level 1                99999
3  2023                     Level 1                99999
4  2023                     Level 1                99999

In [32]:
data.iloc[0:10,3:]

Industry_name_NZSIOC               Units Variable_code  \
0       All industries  Dollars (millions)           H01   
1       All industries  Dollars (millions)           H04   
2       All industries  Dollars (millions)           H05   
3       All industries  Dollars (millions)           H07   
4       All industries  Dollars (millions)           H08   
5       All industries  Dollars (millions)           H09   
6       All industries  Dollars (millions)           H10   
7       All industries  Dollars (millions)           H11   
8       All industries  Dollars (millions)           H12   
9       All industries  Dollars (millions)           H13   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   
5                           Interest and donations  Financial performance   
6                                   Indirect taxes  Financial performance   
7                                     Depreciation  Financial performance   
8                          Salaries and wages paid  Financial performance   
9                         Redundancy and severance  Financial performance   

    Value                             Industry_code_ANZSIC06  
0  930995  ANZSIC06 divisions A-S (excluding classes K633...  
1  821630  ANZSIC06 divisions A-S (excluding classes K633...  
2   84354  ANZSIC06 divisions A-S (excluding classes K633...  
3   25010  ANZSIC06 divisions A-S (excluding classes K633...  
4  832964  ANZSIC06 divisions A-S (excluding classes K633...  
5   55267  ANZSIC06 divisions A-S (excluding classes K633...  
6    7426  ANZSIC06 divisions A-S (excluding classes K633...  
7   30814  ANZSIC06 divisions A-S (excluding classes K633...  
8  147663  ANZSIC06 divisions A-S (excluding classes K633...  
9     269  ANZSIC06 divisions A-S (excluding classes K633...

In [38]:
data.head()

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2023                     Level 1                99999       All industries   
1  2023                     Level 1                99999       All industries   
2  2023                     Level 1                99999       All industries   
3  2023                     Level 1                99999       All industries   
4  2023                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   

    Value                             Industry_code_ANZSIC06  
0  930995  ANZSIC06 divisions A-S (excluding classes K633...  
1  821630  ANZSIC06 divisions A-S (excluding classes K633...  
2   84354  ANZSIC06 divisions A-S (excluding classes K633...  
3   25010  ANZSIC06 divisions A-S (excluding classes K633...  
4  832964  ANZSIC06 divisions A-S (excluding classes K633...

In [42]:
data.loc[0:3,("Year","Units")]

Year               Units
0  2023  Dollars (millions)
1  2023  Dollars (millions)
2  2023  Dollars (millions)
3  2023  Dollars (millions)

In [46]:
data.drop("Variable_name", axis=1)

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2023                     Level 1                99999   
1      2023                     Level 1                99999   
2      2023                     Level 1                99999   
3      2023                     Level 1                99999   
4      2023                     Level 1                99999   
...     ...                         ...                  ...   
50980  2013                     Level 3                 ZZ11   
50981  2013                     Level 3                 ZZ11   
50982  2013                     Level 3                 ZZ11   
50983  2013                     Level 3                 ZZ11   
50984  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
1                  All industries  Dollars (millions)           H04   
2                  All industries  Dollars (millions)           H05   
3                  All industries  Dollars (millions)           H07   
4                  All industries  Dollars (millions)           H08   
...                           ...                 ...           ...   
50980  Food product manufacturing          Percentage           H37   
50981  Food product manufacturing          Percentage           H38   
50982  Food product manufacturing          Percentage           H39   
50983  Food product manufacturing          Percentage           H40   
50984  Food product manufacturing          Percentage           H41   

           Variable_category   Value  \
0      Financial performance  930995   
1      Financial performance  821630   
2      Financial performance   84354   
3      Financial performance   25010   
4      Financial performance  832964   
...                      ...     ...   
50980       Financial ratios      52   
50981       Financial ratios      40   
50982       Financial ratios      12   
50983       Financial ratios       5   
50984       Financial ratios      46   

                                  Industry_code_ANZSIC06  
0      ANZSIC06 divisions A-S (excluding classes K633...  
1      ANZSIC06 divisions A-S (excluding classes K633...  
2      ANZSIC06 divisions A-S (excluding classes K633...  
3      ANZSIC06 divisions A-S (excluding classes K633...  
4      ANZSIC06 divisions A-S (excluding classes K633...  
...                                                  ...  
50980  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50981  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50982  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50983  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50984  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[50985 rows x 9 columns]

In [50]:
data.drop([1,2,3,4],axis=0)

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2023                     Level 1                99999   
5      2023                     Level 1                99999   
6      2023                     Level 1                99999   
7      2023                     Level 1                99999   
8      2023                     Level 1                99999   
...     ...                         ...                  ...   
50980  2013                     Level 3                 ZZ11   
50981  2013                     Level 3                 ZZ11   
50982  2013                     Level 3                 ZZ11   
50983  2013                     Level 3                 ZZ11   
50984  2013                     Level 3                 ZZ11   

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01   
5                  All industries  Dollars (millions)           H09   
6                  All industries  Dollars (millions)           H10   
7                  All industries  Dollars (millions)           H11   
8                  All industries  Dollars (millions)           H12   
...                           ...                 ...           ...   
50980  Food product manufacturing          Percentage           H37   
50981  Food product manufacturing          Percentage           H38   
50982  Food product manufacturing          Percentage           H39   
50983  Food product manufacturing          Percentage           H40   
50984  Food product manufacturing          Percentage           H41   

                             Variable_name      Variable_category   Value  \
0                             Total income  Financial performance  930995   
5                   Interest and donations  Financial performance   55267   
6                           Indirect taxes  Financial performance    7426   
7                             Depreciation  Financial performance   30814   
8                  Salaries and wages paid  Financial performance  147663   
...                                    ...                    ...     ...   
50980                          Quick ratio       Financial ratios      52   
50981  Margin on sales of goods for resale       Financial ratios      40   
50982                     Return on equity       Financial ratios      12   
50983               Return on total assets       Financial ratios       5   
50984                Liabilities structure       Financial ratios      46   

                                  Industry_code_ANZSIC06  
0      ANZSIC06 divisions A-S (excluding classes K633...  
5      ANZSIC06 divisions A-S (excluding classes K633...  
6      ANZSIC06 divisions A-S (excluding classes K633...  
7      ANZSIC06 divisions A-S (excluding classes K633...  
8      ANZSIC06 divisions A-S (excluding classes K633...  
...                                                  ...  
50980  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50981  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50982  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50983  ANZSIC06 groups C111, C112, C113, C114, C115, ...  
50984  ANZSIC06 groups C111, C112, C113, C114, C115, ...  

[50981 rows x 10 columns]

In [58]:
data.min()

Year                                                2013
Industry_aggregation_NZSIOC                      Level 1
Industry_code_NZSIOC                               99999
Industry_name_NZSIOC                       Accommodation
Units                                            Dollars
Variable_code                                        H01
Variable_name                  Additions to fixed assets
Variable_category                  Financial performance
Value                                                 -1
Industry_code_ANZSIC06               ANZSIC06 Group F380
dtype: object

In [62]:
data.max()

Year                                                           2023
Industry_aggregation_NZSIOC                                 Level 4
Industry_code_NZSIOC                                           ZZ11
Industry_name_NZSIOC                     Wood Product Manufacturing
Units                                                    Percentage
Variable_code                                                   H41
Variable_name                       Total income per employee count
Variable_category                                  Financial ratios
Value                                                             S
Industry_code_ANZSIC06         ANZSIC06 groups S951, S952, and S953
dtype: object

In [78]:
data.head()

Year Industry_aggregation_NZSIOC Industry_code_NZSIOC Industry_name_NZSIOC  \
0  2023                     Level 1                99999       All industries   
1  2023                     Level 1                99999       All industries   
2  2023                     Level 1                99999       All industries   
3  2023                     Level 1                99999       All industries   
4  2023                     Level 1                99999       All industries   

                Units Variable_code  \
0  Dollars (millions)           H01   
1  Dollars (millions)           H04   
2  Dollars (millions)           H05   
3  Dollars (millions)           H07   
4  Dollars (millions)           H08   

                                     Variable_name      Variable_category  \
0                                     Total income  Financial performance   
1  Sales, government funding, grants and subsidies  Financial performance   
2                Interest, dividends and donations  Financial performance   
3                             Non-operating income  Financial performance   
4                                Total expenditure  Financial performance   

    Value                             Industry_code_ANZSIC06  
0  930995  ANZSIC06 divisions A-S (excluding classes K633...  
1  821630  ANZSIC06 divisions A-S (excluding classes K633...  
2   84354  ANZSIC06 divisions A-S (excluding classes K633...  
3   25010  ANZSIC06 divisions A-S (excluding classes K633...  
4  832964  ANZSIC06 divisions A-S (excluding classes K633...

In [80]:
def double(s):
     return s*2

In [90]:
data[('Year')].apply(double)

0        4046
1        4046
2        4046
3        4046
4        4046
         ... 
50980    4026
50981    4026
50982    4026
50983    4026
50984    4026
Name: Year, Length: 50985, dtype: int64

In [92]:
def half(s):
    return s*0.5

In [112]:
data[("Year")].apply(half)

0        1011.5
1        1011.5
2        1011.5
3        1011.5
4        1011.5
          ...  
50980    1006.5
50981    1006.5
50982    1006.5
50983    1006.5
50984    1006.5
Name: Year, Length: 50985, dtype: float64

In [124]:
import pandas as pd

In [130]:
s1=pd.Series([1,2,3,4,5])

In [134]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [142]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [146]:
s1=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [150]:
s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [152]:
s1=pd.Series({'a':10,'b':20,'c':30})

In [156]:
s1

a    10
b    20
c    30
dtype: int64

In [158]:
s1=pd.Series([1,2,3,4,5,6,7,8,9])

In [162]:
s1[3]

4

In [166]:
s1[-3:]

6    7
7    8
8    9
dtype: int64

In [170]:
s1[2:5]

2    3
3    4
4    5
dtype: int64

In [174]:
s1[:4]

0    1
1    2
2    3
3    4
dtype: int64

In [180]:
s1[1:9:2]

1    2
3    4
5    6
7    8
dtype: int64

In [182]:
arr=s1+10

In [184]:
arr

0    11
1    12
2    13
3    14
4    15
5    16
6    17
7    18
8    19
dtype: int64

In [186]:
arr=s1*10

In [188]:
arr

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [190]:
s1=pd.Series([10,20,30,40,50])

In [194]:
arr=s1-5

In [196]:
arr

0     5
1    15
2    25
3    35
4    45
dtype: int64

In [198]:
arr=s1/2

In [202]:
arr

0     5.0
1    10.0
2    15.0
3    20.0
4    25.0
dtype: float64

In [204]:
s1=pd.Series([1,2,3,4,5])

In [208]:
s2=pd.Series([10,20,30,40,50])

In [210]:
yash=s1+s2

In [214]:
yash

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [218]:
yash=s2-s1
yash

0     9
1    18
2    27
3    36
4    45
dtype: int64

In [222]:
yash=s1*s2
yash

0     10
1     40
2     90
3    160
4    250
dtype: int64

In [224]:
import numpy as np

In [228]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [244]:
np.full((2,3),55)

array([[55, 55, 55],
       [55, 55, 55]])

In [248]:
np.arange(1,5)

array([1, 2, 3, 4])

In [252]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [258]:
np.random.randint(1,100)

91

In [262]:
np.random.randint(1,100,5)

array([54, 67, 55, 73, 50])

In [264]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

In [268]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [272]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [276]:
np.vstack((n2,n1))

array([[40, 50, 60],
       [10, 20, 30]])

In [284]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [298]:
np.column_stack((n2,n1))

array([[40, 10],
       [50, 20],
       [60, 30]])

In [302]:
np.intersect1d(n1,n2)

array([], dtype=int32)

In [304]:
n1=np.array([1,2,3,4,5])
n2=np.array([4,5,6,7,8])

In [310]:
np.intersect1d(n1,n2)

array([4, 5])

In [314]:
np.setdiff1d(n1,n2)

array([1, 2, 3])

In [320]:
np.setdiff1d(n2,n1)

array([6, 7, 8])

In [324]:
np.sum([n1,n2])

45

In [328]:
n1=np.array([10,20])
n2=np.array([30,40])

In [332]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [336]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [340]:
n1=n1+1

In [344]:
n1

array([12, 22])

In [348]:
n1-1

array([11, 21])

In [352]:
n1-1

array([11, 21])

In [356]:
n1=n1-1

In [360]:
n1

array([10, 20])

In [366]:
n1*2

array([20, 40])

In [370]:
n1=np.array([10,20,30,40,50,60,70,80,90])

In [374]:
np.mean(n1)

50.0

In [378]:
np.median(n1)

50.0

In [384]:
np.min(n1)

10

In [ ]:
np.max()